---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 114514.
--- DateTime: 2026/2/19 19:50
---
local toggle_key     = 8           -- 侧键开关 (G8)
local led_key        = "capslock"  -- 状态指示灯
local pull_step      = 1           -- 下拉像素(强制保持1，保证跟枪极致平滑)
local pull_delay     = 12          -- 下拉延迟(ms)，数字越小压得越狠
local max_pull_count = 280         -- 最大下拉次数 (约对应3.3秒打空30发弹匣)

local is_active      = false       -- 默认关闭

-- 初始化
EnablePrimaryMouseButtonEvents(true)
ClearLog()
OutputLogMessage("76平滑压枪已加载。\n", toggle_key)

-- 同步灯光状态
function SyncLedState(target_state)
    if IsKeyLockOn(led_key) ~= target_state then
        PressAndReleaseKey(led_key)
    end
end

-- 主逻辑
function OnEvent(event, arg)
    -- 开关切换
    if (event == "MOUSE_BUTTON_PRESSED" and arg == toggle_key) then
        is_active = not is_active

        if is_active then
            OutputLogMessage("76压枪：开启\n")
            SyncLedState(true)
        else
            OutputLogMessage("76压枪：关闭\n")
            SyncLedState(false)
        end
    end

    -- 射击与纯垂直压枪
    if (event == "MOUSE_BUTTON_PRESSED" and arg == 1 and is_active) then
        local pull_counter = 0

        repeat
            pull_counter = pull_counter + 1

            if (pull_counter <= max_pull_count) then
                -- 平滑下拉
                MoveMouseRelative(0, pull_step)
                Sleep(pull_delay)
            else
                -- 弹匣打空后不再下拉
                Sleep(10)
            end

        until not IsMouseButtonPressed(1)
    end
end