---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 114514.
--- DateTime: 2026/2/19 19:36
---
local bhop_key  = 5           -- 触发按键 (默认鼠标侧键 G5)
local jump_key  = "spacebar"  -- 游戏内跳跃键
local min_delay = 12          -- 最小随机延迟 (ms)
local max_delay = 28          -- 最大随机延迟 (ms)

EnablePrimaryMouseButtonEvents(true)
ClearLog()
OutputLogMessage("Apex 身法脚本已加载。\n", bhop_key)

function OnEvent(event, arg)
    -- 侧键长按触发
    if (event == "MOUSE_BUTTON_PRESSED" and arg == bhop_key) then
        OutputLogMessage("连跳开始...\n")

        repeat
            PressAndReleaseKey(jump_key)

            Sleep(math.random(min_delay, max_delay))

        until not IsMouseButtonPressed(bhop_key)

        OutputLogMessage("连跳停止。\n")
    end
end