---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 114514.
--- DateTime: 2026/2/19 19:26
---

local trigger_key    = 8     -- 触发按键
local click_interval = 50    -- 每次右键点击的间隔时间（单位：毫秒）

function OnEvent(event, arg)
    if (event == "MOUSE_BUTTON_PRESSED" and arg == trigger_key) then

        repeat
            PressAndReleaseMouseButton(2)

            -- 间隔
            Sleep(click_interval)

            -- 松开退出循环
        until not IsMouseButtonPressed(trigger_key)
    end
end