---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 114514.
--- DateTime: 2026/2/17 19:17
---
EnablePrimaryMouseButtonEvents(true)

-- === 配置区域 ===
local enable = false        -- 默认关闭
local toggle_key = 8        -- 开关：G8键

-- 这里填你在游戏里绑定的副开火键
local rapid_fire_key = "]"

-- 连点速度 (毫秒)
local min_delay = 50
local max_delay = 80

function OnEvent(event, arg)
    -- 1. 开关控制 (G8)
    if (event == "MOUSE_BUTTON_PRESSED" and arg == toggle_key) then
        enable = not enable
        if enable then
            OutputLogMessage(">>> 极限射速: ON\n")
            if not IsKeyLockOn("capslock") then PressAndReleaseKey("capslock") end
        else
            OutputLogMessage("<<< 极限射速: OFF\n")
            if IsKeyLockOn("capslock") then PressAndReleaseKey("capslock") end
        end
    end

    -- 2. 核心逻辑
    if (event == "MOUSE_BUTTON_PRESSED" and arg == 1) then
        -- 只有在【开启】状态下才执行
        if enable then
            repeat
                -- 模拟按下键盘上的 ] 键
                PressAndReleaseKey(rapid_fire_key)

                -- 随机延迟
                Sleep(math.random(min_delay, max_delay))

            until not IsMouseButtonPressed(1) -- 松开左键停止
        end
    end
end